FEG-231 - feature - tabs
iamproperty/iamproperty.github.io pull request #319
Opened 2023-09-29 09:38 UTC by arthurrigley

## Summary of Changes
1. Add disabled tab
2. Updated and improved overall styling
- Add mobile horizontal scroll (on non admin panel)
- Dark mode styling
5. Update admin panel (small amount to change)
6. Update version control table
7. Add pdf download
8. Update README areas

## Review
Open up the preview site (see the below netlify comment below) and navigate to:
- /components/tabs

## Ticket(s)
FEG-231

## Checklist

The below needs to be done before a pull request can be approved:

- [x] The pull request command has been ran `npm run pull-request`
- [ ] New components work as a Vue component, Web component -and as static HTML-
- [ ] New components added as an export to src/index.js
- [ ] New components/features have sufficient unit tests
- [ ] New components/features have sufficient documentation
- [ ] New component has dataLayer events added
- [ ] New component is added to the rollup config

## Accesibility check list

- [ ] New components/features are accessible to keyboard users (All links/buttons are tabbable, All content is accessible)
- [ ] New components/features are accessible to non-JS users (All links/buttons are tabbable, All content is accessible), this may have visual differences
- [ ] New components/features have hover, focus and active states on all the links/buttons
- [ ] New components/features work when in dark mode and high contrast mode. Buttons, links and icons should still look like what they are.

2023-10-02 10:54 UTC, JamesLambert1986 requested changes
Can you deal with the very minor things i've added aswell as get an approval from Mark.

It would be good to get the missing content in first aswell then you can take the (beta) text from the routing file.

2023-10-02 10:54 UTC, JamesLambert1986 commented on assets/sass/components/tabs.scss
> +    margin: 0;// 0.5rem 1.5rem 0 0;
Can the comment be removed.

2023-10-02 10:54 UTC, JamesLambert1986 commented on docs/views/components/TabsDoc.vue
> +  //import anatomy from ''
Remove this line

2023-10-02 10:54 UTC, JamesLambert1986 commented on src/components/Tabs/Tabs.vue
> +import iamTabs from '../../../assets/js/components/tabs/tabs.component.js'
Can we put the .min back please. I know this is annoying and ill try to come up with dev/production flag or something in the future.

2023-10-03 09:56 UTC, natwalker-iap requested changes

2023-10-03 09:56 UTC, natwalker-iap commented on assets/ts/components/tabs/tabs.component.ts
> +    // let buttons = this.shadowRoot.querySelector('.link')
can these comments be removed? (46-49)

2023-10-03 11:01 UTC, arthurrigley commented
@JamesLambert1986  @natwalker-iap  - thanks for comments. I've done the following under the latest commit:

- Add the anatomy image
- Remove the beta from route name
- Remove unneccesary comments
- Re-add .min file
- Add new PDF
- Update text from new PDF
- run `npm run pull-request`

2023-10-03 16:05 UTC, JamesLambert1986 approved these changes

2023-10-03 16:40 UTC, merged