FEG-116/feature/form range field
iamproperty/iamproperty.github.io pull request #336
Opened 2023-11-06 14:24 UTC by JamesLambert1986

## Summary of Changes
1. Updated the CSS for the input range field
2. Create a slider component to enhance the functionality

## Review
Open up the preview site (see the below netlify comment below) and navigate to:
- /form/range
- /components/slider

## Ticket(s)
FEG-116

## Checklist

The below needs to be done before a pull request can be approved:

- [ ] The pull request command has been ran `npm run pull-request`
- [ ] New components work as a Vue component, Web component and as static HTML
- [ ] New components added as an export to src/index.js
- [ ] New components/features have sufficient unit tests
- [ ] New components/features have sufficient documentation
- [ ] New component has dataLayer events added
- [ ] New component is added to the rollup config

## Accesibility check list

- [ ] New components/features are accessible to keyboard users (All links/buttons are tabbable, All content is accessible)
- [ ] New components/features are accessible to non-JS users (All links/buttons are tabbable, All content is accessible), this may have visual differences
- [ ] New components/features have hover, focus and active states on all the links/buttons
- [ ] New components/features work when in dark mode and high contrast mode. Buttons, links and icons should still look like what they are.

2023-11-06 16:15 UTC, natwalker-iap requested changes

2023-11-06 16:15 UTC, natwalker-iap commented on assets/sass/components/slider.scss
> +  //width: 200%;
can these commented out styles come out?

2023-11-06 18:52 UTC, JamesLambert1986 commented on assets/sass/components/slider.scss
> +  //width: 200%;
Yes they can

2023-11-07 09:04 UTC, natwalker-iap approved these changes

2023-11-08 10:44 UTC, merged